=== ananyaa845/web_technology/XML/note.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Definition of main"note"element -->
    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="to" type="xs:string"/>
                <xs:element name="from" type="xs:string"/>
                <xs:element name="heading" type="xs:string"/>
                <xs:element name="body" type="xs:string"/>
                <xs:element name="date" type="xs:string">
                <xs:element name="priority" type="xs:decimal">
                <xs:element name="urgent" type="xs:boolean">
            </xs:sequence>
            <!-- An attribute with a enumerated type  -->
            <xs:attribute name="id" type"xs:positiveInteger">
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ananyaa845/web_technology/XML/notexsd.xml
<?xml version="1.0"?>
<note xmlns:xsi ="http://www.w3org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="note.xsd"
id="1001">
    <to>Shyam</to>
    <from>Ram</from>
    <heading>Meeting</heading>
    <body>Dont forget tomorrow.</body>
    <date>2026-03-30</date>
    <priority>3.5</priority>
    <urgent>false</urgent>
</note>
